// User-facing copy from POLICY_USER_COPY_V1.md. Internal handoff notes are not rendered.
export type PolicyType = 'privacy' | 'terms' | 'acceptable-use' | 'refunds' | 'support'
type PolicySection = { heading: string; paragraphs: string[] }
type Policy = { eyebrow: string; title: string; intro: string; sections: PolicySection[] }
const section = (heading: string, ...paragraphs: string[]): PolicySection => ({ heading, paragraphs })

export const policies: Record<PolicyType, Policy> = {
  privacy: {
    eyebrow: 'Privacy policy', title: 'Your photos, account and privacy',
    intro: 'This policy explains what Linea processes when you create a coloring page, sign in or contact us. Please avoid using photos or messages that contain sensitive personal information.',
    sections: [
      section('Your photos and coloring pages',
        'The photo-to-coloring tool converts your selected photo in your browser. This tool does not upload your original photo to our server.',
        'It does send a copy of the generated coloring-page PNG to our server so it can be downloaded after an access check. That copy can still contain recognizable details from your photo. Its download link is valid for 24 hours; an expired link does not mean every stored copy has been deleted. Save any available download you want to keep on your own device.',
        'Text-to-coloring generation is not currently available. Do not enter private information into the text box.'),
      section('Google sign-in and account information',
        'When you sign in with Google, we use your Google account identifier, email address and basic profile information to create or recognize your Linea account. We also keep account information such as your subscription status and credit balance.',
        'Google sign-in does not give Linea access to your Google Photos, Drive files, Gmail messages or contacts. Login cookies help keep you signed in and protect the sign-in process. Google handles your Google password; do not send it to us.'),
      section('Payments and support requests',
        'If you use checkout, the payment service handles payment details. Linea keeps transaction references and account-related payment information to track purchases and access. Do not send card numbers or card security codes through our support form.',
        'When you submit a support request, we store your email address, selected category, message and any reference you include. We use those details to review your request and contact you about it. The form does not need your original photo, password or student information.'),
      section('Privacy questions and deletion requests',
        'You can ask about your information or request account-data deletion through [Support](/support). Self-service deletion is not currently available. A request may require verification that the account is yours. Sending a request does not immediately remove an account, cancel a subscription or erase all records. Some payment records may need to be retained where required by law.',
        'For privacy questions, email [support@coloringpageflow.com](mailto:support@coloringpageflow.com). Do not include private photos or identity documents in your first message.'),
    ],
  },
  terms: {
    eyebrow: 'Terms of service', title: 'Using Linea',
    intro: 'These terms explain how to use Linea and what to expect from the service. Use Linea only with content you have the right to use, and follow our [Acceptable use policy](/acceptable-use).',
    sections: [
      section('What the service does',
        'Linea helps adults turn a photo into a black-and-white coloring-page preview. The current photo tool processes the original image in your browser. PNG downloads require Google sign-in and an eligible subscription. Creating a preview does not mean a download is included.',
        'Text-to-coloring generation is not currently available. Batch creation, book production, team accounts and editing tools are not part of the current service. Review a result before printing or sharing it; the conversion may miss details or produce lines you do not want.'),
      section('Your account and content',
        'Use your own Google account to sign in. Keep your account secure and contact us if you notice access you do not recognize. Do not share passwords or sign-in codes with support.',
        "Only choose photos you own or have permission to use. You are responsible for checking any permissions needed for the people and material shown in them. Creating or downloading a coloring page does not give you rights to someone else's image, character or likeness. A paid plan does not, by itself, grant commercial publishing rights."),
      section('Plans, credits and checkout',
        'The pricing page lists monthly plans and credit allowances. Real-money purchases are not currently available. Do not use a checkout that asks for test payment details to make a real purchase.',
        'Before making any future purchase, check the final price, billing frequency and renewal terms shown at checkout. Do not assume that a free preview, a displayed credit balance or returning from checkout means a payment has been completed or download access has been granted. Check your [Account](/account) for the subscription status.',
        'The current browser-based photo preview does not deduct credits. Credits are not cash and cannot be transferred between accounts. If the balance looks wrong, contact support rather than purchasing again to resolve it.'),
      section('Availability and help',
        'Results and access can depend on your browser, connection and the availability of the service. We do not promise uninterrupted access, a fixed completion time or round-the-clock support.',
        'For account, access or billing questions, visit [Support](/support) or email [support@coloringpageflow.com](mailto:support@coloringpageflow.com). For cancellation and refund requests, see [Refunds and cancellation](/refunds). These terms do not limit rights you have under applicable law.'),
    ],
  },
  'acceptable-use': {
    eyebrow: 'Acceptable use policy', title: 'Keep coloring activities safe and respectful',
    intro: 'Linea is for adults preparing coloring activities at home or in a classroom. Use content you have permission to use, and avoid material that could expose, harm or exploit another person.',
    sections: [
      section('Choose content you can use',
        'Use your own photos or photos you have permission to use. Choose subjects suitable for a family or general classroom activity. If a photo shows other people, make sure you have the permission needed to use their image.',
        'For classroom activities, choose objects, animals or scenery rather than identifiable student photos. Children should not create accounts or submit information directly.'),
      section('Do not include private information',
        'Do not submit student photos, student names, class lists, grades, school records or other information that identifies a student. Do not include identity documents, medical information, financial details or other sensitive personal information.',
        'Do not put these details in text prompts or support messages either. A generated coloring page can preserve recognizable features from its original photo, so check the result before sharing it.'),
      section('Content and behavior we do not allow',
        'Do not use Linea for illegal content, sexual exploitation, harassment, threats or material intended to abuse or humiliate someone. Do not use unauthorized images, protected characters or public figures as subjects.',
        "Do not try to bypass sign-in, subscription checks or service limits, access another person's account or results, or interfere with the service. Linea does not offer bulk production, an API for customers or commercial publishing permission."),
      section('Report a concern',
        'If you see content or account activity that may violate this policy, contact us through [Support](/support) or email [support@coloringpageflow.com](mailto:support@coloringpageflow.com).',
        'Describe the concern and include a relevant reference if you have one. Do not resend harmful material or private student information. If you believe a restriction was applied in error, explain what happened so the issue can be reviewed. Reporting a concern does not guarantee a particular outcome or response time.'),
    ],
  },
  refunds: {
    eyebrow: 'Refunds and cancellation', title: 'Help with charges and cancellation',
    intro: 'If you have a question about a charge, missing access or cancellation, contact us before attempting another purchase. Real-money purchases are not currently available on Linea. If you believe you have been charged, send the details below so the issue can be reviewed.',
    sections: [
      section('Request a cancellation',
        'For help with an existing subscription, choose “Payment or subscription” on [Support](/support) or email [support@coloringpageflow.com](mailto:support@coloringpageflow.com).',
        'Include the email you use for Linea and an order or subscription reference if available. Linea does not currently provide a self-service cancellation button. Sending a support message, signing out or requesting account deletion does not itself cancel a subscription. Ask for confirmation of the cancellation and the date it takes effect.'),
      section('Ask for a refund review',
        'Contact us if you believe you were charged twice, paid without receiving access, or have another billing problem. Include the payment date, amount, currency and order reference if you have one. Explain what happened and whether you can access the service.',
        'Refund requests are reviewed individually. We do not promise that every request will qualify, that a full refund will be issued, or that a refund will arrive within a fixed number of days. Nothing on this page limits refund rights you have under applicable law.'),
      section('Missing access or an unexpected balance',
        'If you return from checkout but your account does not show the expected subscription or credits, do not assume another payment is needed. Check your [Account](/account), then contact support with the reference and the time of the attempt.',
        'A failed preview or expired download is not automatic proof of a charge. Explain what you saw so the access problem and any payment question can be reviewed separately.'),
      section('Protect your payment information',
        'Never send a full card number, card security code, bank login, password or sign-in code. If a receipt is needed later, remove sensitive information before sharing it. Do not include payment screenshots or private documents in the initial form message.',
        'Use [Support](/support) or [support@coloringpageflow.com](mailto:support@coloringpageflow.com) for refund and cancellation questions. Keep any request reference you receive.'),
    ],
  },
  support: {
    eyebrow: 'Support', title: 'Tell us what went wrong',
    intro: 'Get help with Google sign-in, subscriptions, coloring pages, billing or privacy. Tell us what happened and include a request or order reference if you have one. You do not need to sign in to contact Support.',
    sections: [
      section('Account and sign-in', 'Tell us which page you were using and what happened when you tried to sign in. Include the error message if it does not contain private information. Do not send your Google password, sign-in code or a full sign-in link.'),
      section('Payments and subscriptions', 'Use the email associated with your Linea account and include an order or subscription reference if available. For a possible charge, include the date, amount and currency. Do not make another purchase just to fix missing access. See [Refunds and cancellation](/refunds) for billing requests.'),
      section('Coloring pages and downloads',
        'Tell us whether the problem happened while creating a photo preview or downloading a PNG. Include a result or job reference if you have one, along with your browser name and the approximate time of the problem. Do not attach or paste your original photo.',
        'PNG downloads require Google sign-in and an eligible subscription. A generated preview is available for download for 24 hours; if it has expired, create a new preview. Text-to-coloring generation is not currently available.'),
      section('Privacy, complaints and other questions',
        'Choose “Privacy or data deletion” for questions about your information. Choose “Refund request” for a refund review or “Complaint or policy concern” to report a problem with the service or its content.',
        'Do not send student information, sensitive photos, identity documents or full payment details. You can also email [support@coloringpageflow.com](mailto:support@coloringpageflow.com). We do not guarantee an immediate reply or offer round-the-clock support.'),
      section('What happens after you send a request',
        'A successful submission gives you a request reference. It is not a confirmation that a refund, cancellation or deletion has been completed. Keep the reference and the email address you used when you submitted the form. Do not rely on receiving an automatic confirmation email.',
        'For another contact option, email [support@coloringpageflow.com](mailto:support@coloringpageflow.com).'),
    ],
  },
}
