interface CloudflareEnv {
  PAYMENT_PROVIDER?: 'creem' | 'waffo'
  WAFFO_MODE?: 'test'
  WAFFO_MERCHANT_ID?: string
  WAFFO_PRIVATE_KEY_TEST?: string
  WAFFO_STORE_ID_TEST?: string
  WAFFO_WEBHOOK_PUBLIC_KEY_TEST?: string
  WAFFO_PRODUCT_STARTER_TEST?: string
  WAFFO_PRODUCT_STANDARD_TEST?: string
  WAFFO_PRODUCT_PREMIUM_TEST?: string
  GOOGLE_CLIENT_ID?: string
  GOOGLE_CLIENT_SECRET?: string
  AUTH_SECRET?: string
  CREEM_API_KEY?: string
  CREEM_WEBHOOK_SECRET?: string
  CREEM_PRODUCT_STARTER_MONTHLY?: string
  CREEM_PRODUCT_STANDARD_MONTHLY?: string
  CREEM_PRODUCT_PREMIUM_MONTHLY?: string
}
